# Generated by Django 4.1.5 on 2023-01-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Food_model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("food_name", models.CharField(max_length=100)),
                ("food_date", models.DateField(verbose_name="Date eaten:")),
                ("food_time", models.TimeField(verbose_name="Time eaten:")),
                ("food_calories", models.IntegerField(default=0)),
                ("food_protein", models.IntegerField(default=0)),
                ("food_fat", models.IntegerField(default=0)),
                ("food_saturatedfat", models.IntegerField(default=0)),
                ("food_sodium", models.IntegerField(default=0)),
                ("food_carb", models.IntegerField(default=0)),
                ("food_fiber", models.IntegerField(default=0)),
            ],
        ),
    ]
